{
  "openapi": "3.0.3",
  "info": {
    "title": "Phrase API Reference",
    "version": "2.0.0",
    "description": "Phrase is a translation management platform for software projects. You can collaborate on language file translation with your team or order translations through our platform. The API allows you to import locale files, download locale files, tag keys or interact in other ways with the localization data stored in Phrase for your account.\n## API Endpoint\n<div class=\"resource__code--outer\">\n  <div class=\"code-section\">\n    <pre><code>https://api.phrase.com/v2/</code></pre>\n  </div>\n</div>\nThe API is only accessible via HTTPS, the base URL is <code>https://api.phrase.com/</code>, and the current version is <code>v2</code> which results in the base URL for all requests: <code>https://api.phrase.com/v2/</code>.\n\n## Usage\n[curl](http://curl.haxx.se/) is used primarily to send requests to Phrase in the examples. On most you'll find a second variant using the [Phrase API v2 client](https://phrase.com/cli/) that might be more convenient to handle. For further information check its [documentation](https://help.phrase.com/help/phrase-in-your-terminal).\n\n## Use of HTTP Verbs\nPhrase API v2 tries to use the appropriate HTTP verb for accessing each endpoint according to REST specification where possible:\n<div class=\"table-responsive\">\n  <table class=\"basic-table\">\n    <thead>\n      <tr class=\"basic-table__row basic-table__row--header\">\n        <th class=\"basic-table__cell basic-table__cell--header\">Verb</th>\n        <th class=\"basic-table__cell basic-table__cell--header\">Description</th>\n      </tr>\n    </thead>\n    <tbody>\n      <tr>\n        <td class=\"basic-table__cell\">GET</td>\n        <td class=\"basic-table__cell\">Retrieve one or multiple resources</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">POST</td>\n        <td class=\"basic-table__cell\">Create a resource</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">PUT</td>\n        <td class=\"basic-table__cell\">Update a resource</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">PATCH</td>\n        <td class=\"basic-table__cell\">Update a resource (partially)</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">DELETE</td>\n        <td class=\"basic-table__cell\">Delete a resource</td>\n      </tr>\n    </tbody>\n  </table>\n</div>\n\n## Identification via User-Agent\nYou must include the User-Agent header with the name of your application or project. It might be a good idea to include some sort of contact information  as well, so that we can get in touch if necessary (e.g. to warn you about Rate-Limiting or badly formed requests). Examples of excellent User-Agent headers:\n<pre><code>User-Agent: Frederiks Mobile App (frederik@phrase.com) User-Agent: ACME Inc Python Client (http://example.com/contact)</code></pre>\nIf you don't send this header, you will receive a response with 400 Bad Request.\n\n## Lists\nWhen you request a list of resources, the API will typically only return an array of resources including their most important attributes. For a detailed representation of the resource you should request its detailed representation.\nLists are usually [paginated](#pagination).\n\n## Parameters\nMany endpoints support additional parameters, e.g. for pagination. When passing them in a GET request you can send them as HTTP query string parameters:\n<pre><code>$ curl -u EMAIL_OR_ACCESS_TOKEN \"https://api.phrase.com/v2/projects?page=2\"</code></pre>\nWhen performing a POST, PUT, PATCH or DELETE request, we recommend sending parameters that are not already included in the URL, as JSON body:\n<pre><code>$ curl -H 'Content-Type: application/json' -d '{\"name\":\"My new project\"}' -u EMAIL_OR_ACCESS_TOKEN https://api.phrase.com/v2/projects</code></pre>\nEncoding parameters as JSON means better support for types (boolean, integer) and usually better readability. Don't forget to set the correct Content-Type for your request.\n*The Content-Type header is omitted in some of the following examples for better readbility.*\n\n## Errors\n\n### Request Errors\nIf a request contains invalid JSON or is missing a required parameter (besides resource attributes), the status `400 Bad Request` is returned:\n<pre><code>{\n  \"message\": \"JSON could not be parsed\"\n}</code></pre>\n\n### Validation Errors\nWhen the validation for a resource fails, the status `422 Unprocessable Entity` is returned, along with information on the affected fields:\n<pre><code>{\n  \"message\": \"Validation Failed\",\n  \"errors\": [\n    {\n      \"resource\": \"Project\",\n      \"field\": \"name\",\n      \"message\": \"can't be blank\"\n    }\n  ]\n}</code></pre>\n\n## Date Format\nTimes and dates are returned and expected in [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) date format:\n<pre><code>YYYY-MM-DDTHH:MM:SSZ</code></pre>\nInstead of 'Z' for UTC time zone you can specify your time zone's locale offset using the following notation:\n<pre><code>YYYY-MM-DDTHH:MM:SS¬±hh:mm</code></pre>\nExample for CET (1 hour behind UTC):\n<pre><code>2015-03-31T13:00+01:00</code></pre>\nPlease note that in HTTP headers, we will use the appropriate recommended date formats instead of ISO 8601.\n\n## Authentication options\n<div class=\"alert alert-info\">For more detailed information on authentication, check out the <a href=\"#authentication\">API v2 Authentication Guide</a>.</div>\nThere are two different ways to authenticate when performing API requests:\n* E-Mail and password * Oauth Access Token\n\n### E-Mail and password\nTo get started easily, you can use HTTP Basic authentication with your email and password:\n<pre><code>$ curl -u username:password \"https://api.phrase.com/v2/projects\"</code></pre>\n\n### OAuth via Access Tokens\nYou can create and manage access tokens in your [profile settings](https://app.phrase.com/settings/oauth_access_tokens) in Translation Center or via the [Authorizations API](#authorizations).\nSimply pass the access token as the username of your request:\n<pre><code>$ curl -u ACCESS_TOKEN: \"https://api.phrase.com/v2/projects\"</code></pre>\nor send the access token via the `Authorization` header field:\n<pre><code>$ curl -H \"Authorization: token ACCESS_TOKEN\" https://api.phrase.com/v2/projects</code></pre>\nFor more detailed information on authentication, check out the <a href=\"#authentication\">API v2 Authentication Guide</a>.\n## Pagination\nEndpoints that return a list or resources will usually return paginated results and include 25 items by default. To access further pages, use the `page` parameter:\n<pre><code>$ curl -u EMAIL_OR_ACCESS_TOKEN \"https://api.phrase.com/v2/projects?page=2\"</code></pre>\nSome endpoints also allow a custom page size by using the `per_page` parameter:\n<pre><code>$ curl -u EMAIL_OR_ACCESS_TOKEN \"https://api.phrase.com/v2/projects?page=2&per_page=50\"</code></pre>\nUnless specified otherwise in the description of the respective endpoint, `per_page` allows you to specify a page size up to 100 items.\n\n## Link-Headers\nWe provide you with pagination URLs in the [Link Header field](http://tools.ietf.org/html/rfc5988). Make use of this information to avoid building pagination URLs yourself.\n<pre><code>Link: <https://api.phrase.com/v2/projects?page=1>; rel=\"first\", <https://api.phrase.com/v2/projects?page=3>; rel=\"prev\", <https://api.phrase.com/v2/projects?page=5>; rel=\"next\", <https://api.phrase.com/v2/projects?page=9>; rel=\"last\"</code></pre>\nPossible `rel` values are:\n<div class=\"table-responsive\">\n  <table class=\"basic-table\">\n    <thead>\n      <tr class=\"basic-table__row basic-table__row--header\">\n        <th class=\"basic-table__cell basic-table__cell--header\">Value</th>\n        <th class=\"basic-table__cell basic-table__cell--header\">Description</th>\n      </tr>\n    </thead>\n    <tbody>\n      <tr>\n        <td class=\"basic-table__cell\">next</td>\n        <td class=\"basic-table__cell\">URL of the next page of results</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">last</td>\n        <td class=\"basic-table__cell\">URL of the last page of results</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">first</td>\n        <td class=\"basic-table__cell\">URL of the first page of results</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\">prev</td>\n        <td class=\"basic-table__cell\">URL of the previous page of results</td>\n      </tr>\n    </tbody>\n  </table>\n</div>\n## Rate Limiting\nAll API endpoints are subject to rate limiting to ensure good performance for all customers. The rate limit is calculated per user:\n* 1000 requests per 5 minutes * 4 concurrent (parallel) requests\nFor your convenience we send information on the current rate limit within the response headers:\n<div class=\"table-responsive\">\n  <table class=\"basic-table\">\n    <thead>\n      <tr class=\"basic-table__row basic-table__row--header\">\n        <th class=\"basic-table__cell basic-table__cell--header\">Header</th>\n        <th class=\"basic-table__cell basic-table__cell--header\">Description</th>\n      </tr>\n    </thead>\n    <tbody>\n      <tr>\n        <td class=\"basic-table__cell\" style=\"white-space: nowrap;\"><code>X-Rate-Limit-Limit</code></td>\n        <td class=\"basic-table__cell\">Number of max requests allowed in the current time period</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\" style=\"white-space: nowrap;\"><code>X-Rate-Limit-Remaining</code></td>\n        <td class=\"basic-table__cell\">Number of remaining requests in the current time period</td>\n      </tr>\n      <tr>\n        <td class=\"basic-table__cell\" style=\"white-space: nowrap;\"><code>X-Rate-Limit-Reset</code></td>\n        <td class=\"basic-table__cell\">Timestamp of end of current time period as UNIX timestamp</td>\n      </tr>\n    </tbody>\n  </table>\n</div>\nIf you should run into the rate limit, you will receive the HTTP status code `429: Too many requests`.\nIf you should need higher rate limits, [contact us](https://phrase.com/contact).\n\n## Conditional GET requests / HTTP Caching\n<div class=\"alert alert-info\"><p><strong>Note:</strong> Conditional GET requests are currently only supported for <a href=\"#locales_download\">locales#download</a> and <a href=\"#translations_index\">translations#index</a></p></div>\nWe will return an ETag or Last-Modified header with most GET requests. When you request a resource we recommend to store this value and submit them on subsequent requests as `If-Modified-Since` and `If-None-Match` headers. If the resource has not changed in the meantime, we will return the status `304 Not Modified` instead of rendering and returning the resource again. In most cases this is less time-consuming and makes your application/integration faster.\nPlease note that all conditional requests that return a response with status 304 don't count against your rate limits.\n<pre><code>$ curl -i -u EMAIL_OR_ACCESS_TOKEN \"https://api.phrase.com/v2/projects/1234abcd1234abcdefefabcd1234efab/locales/en/download\" HTTP/1.1 200 OK ETag: \"abcd1234abcdefefabcd1234efab1234\" Last-Modified: Wed, 28 Jan 2015 15:31:30 UTC Status: 200 OK\n$ curl -i -u EMAIL_OR_ACCESS_TOKEN \"https://api.phrase.com/v2/projects/1234abcd1234abcdefefabcd1234efab/locales/en/download\" -H 'If-None-Match: \"abcd1234abcdefefabcd1234efab1234\"' HTTP/1.1 304 Not Modified ETag: \"abcd1234abcdefefabcd1234efab1234\" Last-Modified: Wed, 28 Jan 2015 15:31:30 UTC Status: 304 Not Modified\n$ curl -i -u EMAIL_OR_ACCESS_TOKEN \"https://api.phrase.com/v2/projects/1234abcd1234abcdefefabcd1234efab/locales/en/download\" -H \"If-Modified-Since: Wed, 28 Jan 2015 15:31:30 UTC\" HTTP/1.1 304 Not Modified Last-Modified: Wed, 28 Jan 2015 15:31:30 UTC Status: 304 Not Modified</code></pre>\n\n## JSONP\nThe Phrase API supports [JSONP](http://en.wikipedia.org/wiki/JSONP) for all GET requests in order to deal with cross-domain request issues. Just send a `?callback` parameter along with the request to specify the Javascript function name to be called with the response content:\n<pre><code>$ curl \"https://api.phrase.com/v2/projects?callback=myFunction\"</code></pre>\nThe response will include the normal output for that endpoint, along with a `meta` section including header data:\n<pre><code>myFunction({\n  {\n    \"meta\": {\n      \"status\": 200,\n      ...\n    },\n    \"data\": [\n      {\n        \"id\": \"1234abcd1234abc1234abcd1234abc\"\n        ...\n      }\n    ]\n  }\n});</code></pre>\nTo authenticate a JSONP request, you can send a valid [access token](#authentication) as the `?access_token` parameter along the request:\n<pre><code>$ curl \"https://api.phrase.com/v2/projects?callback=myFunction&access_token=ACCESS-TOKEN\"</code></pre>\n",
    "contact": {
      "name": "Phrase Support",
      "url": "https://developers.phrase.com/api/",
      "email": "support@phrase.com"
    },
    "x-logo": {
      "url": "https://developers.phrase.com/images/phrase-logo.png",
      "backgroundColor": "#0091eb",
      "altText": "Phrase"
    }
  },
  "servers": [
    {
      "url": "https://api.phrase.com/v2"
    }
  ],
  "security": [
    {
      "Token": []
    },
    {
      "Basic": []
    }
  ],
  "tags": [
    {
      "name": "Spaces",
      "description": "Everything about Space"
    }
  ],
  "components": {
    "securitySchemes": {
      "Token": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "description": "Enter your token in the format **token TOKEN**"
      },
      "Basic": {
        "type": "http",
        "scheme": "basic"
      }
    },
    "headers": {
      "X-PhraseApp-OTP": {
        "description": "The number of allowed requests in the current period",
        "schema": {
          "type": "string"
        }
      },
      "X-Rate-Limit-Limit": {
        "description": "The number of allowed requests in the current period",
        "schema": {
          "type": "integer"
        }
      },
      "X-Rate-Limit-Remaining": {
        "description": "The number of remaining requests in the current period",
        "schema": {
          "type": "integer"
        }
      },
      "X-Rate-Limit-Reset": {
        "description": "The number of seconds left in the current period",
        "schema": {
          "type": "integer"
        }
      }
    },
    "schemas": {
      "account": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "company": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "project": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "main_format": {
            "type": "string"
          },
          "project_image_url": {
            "type": "string"
          },
          "account": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        },
        "example": {
          "id": "abcd1234cdef1234abcd1234cdef1234",
          "name": "My Android Project",
          "main_format": "xml",
          "project_image_url": "http://assets.example.com/project.png",
          "account": "account",
          "created_at": "2015-01-28T09:52:53Z",
          "updated_at": "2015-01-28T09:52:53Z"
        }
      },
      "space": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "projects_count": {
            "type": "integer",
            "format": "int32"
          },
          "projects": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/project"
            }
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        },
        "example": {
          "id": "2e7574e8f2372906a03110c2a7cfe671",
          "name": "My first space",
          "created_at": "2020-02-25T12:17:25Z",
          "updated_at": "2020-03-13T14:46:57Z",
          "projects_count": 2,
          "projects": [
            {
              "id": "abcd1234cdef1234abcd1234cdef1234",
              "name": "My Android Project",
              "main_format": "xml",
              "project_image_url": "http://assets.example.com/project.png",
              "account": "account",
              "created_at": "2015-01-28T09:52:53Z",
              "updated_at": "2015-01-28T09:52:53Z"
            },
            {
              "id": "abcd11231fadef1234adacd1234cdef1234",
              "name": "My IOS Project",
              "main_format": "yml",
              "project_image_url": "http://assets.example.com/project2.png",
              "account": "account",
              "created_at": "2015-01-28T09:52:53Z",
              "updated_at": "2015-01-28T09:52:53Z"
            }
          ]
        }
      },
      "errors": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "resource": {
                  "type": "string"
                },
                "field": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        },
        "example": {
          "message": "Validation Failed",
          "errors": [
            {
              "resource": "Resource",
              "field": "name",
              "message": "can't be blank"
            }
          ]
        }
      }
    },
    "parameters": {
      "X-PhraseApp-OTP": {
        "in": "header",
        "name": "X-PhraseApp-OTP",
        "description": "Two-Factor-Authentication token",
        "required": false,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "account_id": {
        "in": "path",
        "name": "account_id",
        "description": "Account ID",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "space_id": {
        "in": "path",
        "name": "space_id",
        "description": "Space ID",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "project_id": {
        "in": "path",
        "name": "project_id",
        "description": "Project ID",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "page": {
        "in": "query",
        "name": "page",
        "description": "Page number",
        "required": false,
        "allowEmptyValue": false,
        "schema": {
          "type": "integer"
        },
        "example": 1
      },
      "per_page": {
        "in": "query",
        "name": "per_page",
        "description": "allows you to specify a page size up to 100 items, 10 by default",
        "required": false,
        "allowEmptyValue": false,
        "schema": {
          "type": "integer"
        },
        "example": 10
      }
    },
    "responses": {
      "204": {
        "description": "The resource was deleted successfully."
      },
      "400": {
        "description": "Bad request"
      },
      "404": {
        "description": "Not Found"
      },
      "422": {
        "description": "Unprocessable entity",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errors"
            }
          }
        }
      },
      "429": {
        "description": "Rate Limiting",
        "headers": {
          "X-Rate-Limit-Limit": {
            "$ref": "#/components/headers/X-Rate-Limit-Limit"
          },
          "X-Rate-Limit-Remaining": {
            "$ref": "#/components/headers/X-Rate-Limit-Remaining"
          },
          "X-Rate-Limit-Reset": {
            "$ref": "#/components/headers/X-Rate-Limit-Reset"
          }
        }
      },
      "503": {
        "description": "Server error"
      }
    }
  },
  "paths": {
    "/accounts/{account_id}/spaces": {
      "get": {
        "summary": "List all Spaces for the given account.",
        "operationId": "spaces",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/per_page"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON array of spaces",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/space"
                  }
                },
                "example": [
                  {
                    "id": "2e7574e8f2372906a03110c2a7cfe671",
                    "name": "My first space",
                    "created_at": "2020-02-25T12:17:25Z",
                    "updated_at": "2020-03-13T14:46:57Z",
                    "projects_count": 2,
                    "projects": [
                      {
                        "id": "abcd1234cdef1234abcd1234cdef1234",
                        "name": "My Android Project",
                        "main_format": "xml",
                        "project_image_url": "http://assets.example.com/project.png",
                        "account": "account",
                        "created_at": "2015-01-28T09:52:53Z",
                        "updated_at": "2015-01-28T09:52:53Z"
                      },
                      {
                        "id": "abcd11231fadef1234adacd1234cdef1234",
                        "name": "My IOS Project",
                        "main_format": "yml",
                        "project_image_url": "http://assets.example.com/project2.png",
                        "account": "account",
                        "created_at": "2015-01-28T09:52:53Z",
                        "updated_at": "2015-01-28T09:52:53Z"
                      }
                    ]
                  },
                  {
                    "id": "2e7574e8f2372906a03110c2a7cfe671",
                    "name": "My first space",
                    "created_at": "2020-02-25T12:17:25Z",
                    "updated_at": "2020-03-13T14:46:57Z",
                    "projects_count": 2,
                    "projects": [
                      {
                        "id": "abcd1234cdef1234abcd1234cdef1234",
                        "name": "My Android Project",
                        "main_format": "xml",
                        "project_image_url": "http://assets.example.com/project.png",
                        "account": "account",
                        "created_at": "2015-01-28T09:52:53Z",
                        "updated_at": "2015-01-28T09:52:53Z"
                      },
                      {
                        "id": "abcd11231fadef1234adacd1234cdef1234",
                        "name": "My IOS Project",
                        "main_format": "yml",
                        "project_image_url": "http://assets.example.com/project2.png",
                        "account": "account",
                        "created_at": "2015-01-28T09:52:53Z",
                        "updated_at": "2015-01-28T09:52:53Z"
                      }
                    ]
                  }
                ]
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces\" \\\n  -u USERNAME_OR_ACCESS_TOKEN\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp spaces list <account_id>"
          }
        ]
      },
      "post": {
        "summary": "Create space",
        "operationId": "space_create",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "My Android Projects"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "A JSON array of space",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/space"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces\" \\\n  -u USERNAME_OR_ACCESS_TOKEN \\\n  -X POST \\\n  -d '{\"name\":\"My Android Projects\"}' \\\n  -H 'Content-Type: application/json'\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp space create <account_id> --name \"My Android Projects\"\n"
          }
        ]
      }
    },
    "/accounts/{account_id}/spaces/{space_id}": {
      "get": {
        "summary": "Get Space",
        "operationId": "space",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/space_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON object of Space",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/space"
                },
                "example": {
                  "id": "2e7574e8f2372906a03110c2a7cfe671",
                  "name": "My first space",
                  "created_at": "2020-02-25T12:17:25Z",
                  "updated_at": "2020-03-13T14:46:57Z",
                  "projects_count": 2,
                  "projects": [
                    {
                      "id": "abcd1234cdef1234abcd1234cdef1234",
                      "name": "My Android Project",
                      "main_format": "xml",
                      "project_image_url": "http://assets.example.com/project.png",
                      "account": "account",
                      "created_at": "2015-01-28T09:52:53Z",
                      "updated_at": "2015-01-28T09:52:53Z"
                    },
                    {
                      "id": "abcd11231fadef1234adacd1234cdef1234",
                      "name": "My IOS Project",
                      "main_format": "yml",
                      "project_image_url": "http://assets.example.com/project2.png",
                      "account": "account",
                      "created_at": "2015-01-28T09:52:53Z",
                      "updated_at": "2015-01-28T09:52:53Z"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces/:id\" \\\n  -u USERNAME_OR_ACCESS_TOKEN\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp space show <account_id> <id>"
          }
        ]
      },
      "patch": {
        "summary": "Update Space",
        "operationId": "space_update",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/space_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "My Android Projects"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A JSON object of Space",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/space"
                },
                "example": {
                  "id": "2e7574e8f2372906a03110c2a7cfe671",
                  "name": "My first space",
                  "created_at": "2020-02-25T12:17:25Z",
                  "updated_at": "2020-03-13T14:46:57Z",
                  "projects_count": 2,
                  "projects": [
                    {
                      "id": "abcd1234cdef1234abcd1234cdef1234",
                      "name": "My Android Project",
                      "main_format": "xml",
                      "project_image_url": "http://assets.example.com/project.png",
                      "account": "account",
                      "created_at": "2015-01-28T09:52:53Z",
                      "updated_at": "2015-01-28T09:52:53Z"
                    },
                    {
                      "id": "abcd11231fadef1234adacd1234cdef1234",
                      "name": "My IOS Project",
                      "main_format": "yml",
                      "project_image_url": "http://assets.example.com/project2.png",
                      "account": "account",
                      "created_at": "2015-01-28T09:52:53Z",
                      "updated_at": "2015-01-28T09:52:53Z"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "422": {
            "$ref": "#/components/responses/422"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces/:id\" \\\n  -u USERNAME_OR_ACCESS_TOKEN \\\n  -X PATCH \\\n  -d '{\"name\":\"My Android Projects\"}' \\\n  -H 'Content-Type: application/json'\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp space update <account_id> <id> --name \"My Android Projects\""
          }
        ]
      },
      "delete": {
        "summary": "Delete Space",
        "operationId": "space_delete",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/space_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          }
        ],
        "responses": {
          "204": {
            "$ref": "#/components/responses/204"
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces/:id\" \\\n  -u USERNAME_OR_ACCESS_TOKEN \\\n  -X DELETE\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp space delete <account_id> <id>"
          }
        ]
      }
    },
    "/accounts/{account_id}/spaces/{space_id}/projects": {
      "get": {
        "summary": "List all projects for the specified Space..",
        "operationId": "space_projects",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/space_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/per_page"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON array of projects",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/project"
                  }
                },
                "example": [
                  {
                    "id": "abcd1234cdef1234abcd1234cdef1234",
                    "name": "My Android Project",
                    "main_format": "xml",
                    "project_image_url": "http://assets.example.com/project.png",
                    "account": "account",
                    "created_at": "2015-01-28T09:52:53Z",
                    "updated_at": "2015-01-28T09:52:53Z"
                  },
                  {
                    "id": "abcd1234cdef1234abcd1234cdef1234",
                    "name": "My Android Project",
                    "main_format": "xml",
                    "project_image_url": "http://assets.example.com/project.png",
                    "account": "account",
                    "created_at": "2015-01-28T09:52:53Z",
                    "updated_at": "2015-01-28T09:52:53Z"
                  }
                ]
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces\" \\\n  -u USERNAME_OR_ACCESS_TOKEN\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp spaces list <account_id>"
          }
        ]
      },
      "post": {
        "summary": "Adds an existing project to the space.",
        "operationId": "space_projects_create",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/space_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": "a4b3c2d1"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "A JSON object of project",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/project"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces/:space_id/projects\" \\\n  -u USERNAME_OR_ACCESS_TOKEN \\\n  -X POST \\\n  -d '{\"id\":\"a4b3c2d1\"}' \\\n  -H 'Content-Type: application/json'\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp spaces projects create <account_id> <space_id> \\ --id a4b3c2d1\n"
          }
        ]
      }
    },
    "/accounts/{account_id}/spaces/{space_id}/projects/{project_id}": {
      "delete": {
        "summary": "Removes a specified project from the specified space.",
        "operationId": "space_project_delete",
        "tags": [
          "Spaces"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/account_id"
          },
          {
            "$ref": "#/components/parameters/space_id"
          },
          {
            "$ref": "#/components/parameters/project_id"
          },
          {
            "$ref": "#/components/parameters/X-PhraseApp-OTP"
          }
        ],
        "responses": {
          "204": {
            "$ref": "#/components/responses/204"
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "429": {
            "$ref": "#/components/responses/429"
          }
        },
        "x-code-samples": [
          {
            "lang": "Curl",
            "source": "curl \"https://api.phrase.com/v2/accounts/:account_id/spaces/:space_id/projects/:id\" \\\n  -u USERNAME_OR_ACCESS_TOKEN \\\n  -X DELETE\n"
          },
          {
            "lang": "CLI",
            "source": "phraseapp spaces projects delete <account_id> <space_id> <id>"
          }
        ]
      }
    }
  }
}

